{
 "title": "TubeArchivist",
 "time": { "from": "2025-06-04T09:04:46.031Z", "to": "2025-06-04T11:17:43.659Z" },
 "panels": [
  { "title": "Subscription Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Playlist Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "yta_playlist_count", "legendFormat": "Playlist Count" }
   ]
  },
  {
   "title": "Channel Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "yta_channel_count", "legendFormat": "Channel Count" }
   ]
  },
  { "title": "Download metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Downloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "yta_download_queue", "legendFormat": "Download Queue" }
   ]
  },
  {
   "title": "Download Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "yta_download_count", "legendFormat": "Download Count" }
   ]
  }
 ]
}